code --install-extension SirTori.indenticator
code --install-extension abusaidm.html-snippets
code --install-extension adamwalzer.string-converter
code --install-extension andys8.jest-snippets
code --install-extension angryobject.react-pure-to-class-vscode
code --install-extension apollographql.vscode-apollo
code --install-extension asvetliakov.snapshot-tools
code --install-extension auchenberg.vscode-browser-preview
code --install-extension bibhasdn.django-html
code --install-extension BriteSnow.vscode-toggle-quotes
code --install-extension burkeholland.simple-react-snippets
code --install-extension capaj.vscode-exports-autocomplete
code --install-extension cduruk.thrift
code --install-extension christian-kohler.npm-intellisense
code --install-extension christian-kohler.path-intellisense
code --install-extension cssho.vscode-svgviewer
code --install-extension dakara.transformer
code --install-extension dbaeumer.vscode-eslint
code --install-extension dracula-theme.theme-dracula
code --install-extension eamodio.find-related
code --install-extension eamodio.gitlens
code --install-extension EditorConfig.EditorConfig
code --install-extension eg2.vscode-npm-script
code --install-extension erichbehrens.pull-request-monitor
code --install-extension esbenp.prettier-vscode
code --install-extension flowtype.flow-for-vscode
code --install-extension formulahendry.auto-close-tag
code --install-extension formulahendry.auto-rename-tag
code --install-extension freakypie.code-python-isort
code --install-extension gcazaciuc.vscode-flow-ide
code --install-extension GitHub.vscode-pull-request-github
code --install-extension gottfired.css2react
code --install-extension ionutvmi.path-autocomplete
code --install-extension JakeBecker.elixir-ls
code --install-extension josephtbradley.hive-sql
code --install-extension jpoissonnier.vscode-styled-components
code --install-extension kumar-harsh.graphql-for-vscode
code --install-extension mikestead.dotenv
code --install-extension mjmcloug.vscode-elixir
code --install-extension mohsen1.prettify-json
code --install-extension mrmlnc.vscode-duplicate
code --install-extension mrmlnc.vscode-stylefmt
code --install-extension ms-mssql.mssql
code --install-extension ms-python.python
code --install-extension ms-vsliveshare.vsliveshare
code --install-extension msjsdiag.debugger-for-chrome
code --install-extension octref.vetur
code --install-extension Orta.vscode-jest
code --install-extension PeterJausovec.vscode-docker
code --install-extension pflannery.vscode-versionlens
code --install-extension PKief.material-icon-theme
code --install-extension planbcoding.vscode-react-refactor
code --install-extension pranaygp.vscode-css-peek
code --install-extension redhat.java
code --install-extension robinbentley.sass-indented
code --install-extension ronnidc.nunjucks
code --install-extension Rubymaniac.vscode-paste-and-indent
code --install-extension sdras.night-owl
code --install-extension Shan.code-settings-sync
code --install-extension shinnn.stylelint
code --install-extension Tyriar.sort-lines
code --install-extension VisualStudioExptTeam.vscodeintellicode
code --install-extension vscjava.vscode-java-debug
code --install-extension vscjava.vscode-java-dependency
code --install-extension vscjava.vscode-java-pack
code --install-extension vscjava.vscode-java-test
code --install-extension vscjava.vscode-maven
code --install-extension wesbos.theme-cobalt2
code --install-extension wix.glean
code --install-extension wmaurer.change-case
code --install-extension wmaurer.vscode-jumpy
code --install-extension xabikos.JavaScriptSnippets
code --install-extension Yummygum.city-lights-icon-vsc
code --install-extension zhuangtongfa.Material-theme
code --install-extension Zignd.html-css-class-completion